name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Idea CLI Inspector
        # You may pin to the exact commit or the version.
        # uses: LionZXY/idea-cli-inspector-actions@c95e240010486247f14c787dd4013e1674d6c3b5
        uses: LionZXY/idea-cli-inspector-actions@v1
